server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3316/mediamanager?useSSL=false&useLegacyDatetimeCode=false
    username: mediamanager
    password: mediamanager
    driverClassName: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    jpa:
      database: MYSQL