server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3336/global?useSSL=false&useLegacyDatetimeCode=false
    username: global
    password: global
    driverClassName: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    jpa:
      database: MYSQL